spring.application.name=auth-service
server.port=8081

# PostgreSQL - auth_db
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=Akash@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=TXlTdXBlclNlY3JldEtleUZvckp3dEF1dGhlbnRpY2F0aW9uUHJvamVjdDEyMzQ1Njc4OQ==
jwt.expiration=900000
jwt.refresh-expiration=604800000

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info
